### ISSUE TITLE
Support for cryptic crossword formats? 

### ISSUE THREAD

**Issue by mixographer** [devottys/xdplayer#18]
I don't know if this software supports cryptic puzzles, but I can't seem to make it read any .puz files for cryptic crosswords. Am I holding it wrong, or is it just not a feature? 

Error I see: 
File "................puz2xd.py", line 45, in gen_xd
IndexError: list index out of range

**Comment by lpesk** [comment]
Hey, sorry about that and thanks for filing an issue! I actually forgot there was a puz->xd converter in here when I added cryptic support to the player. Please let us know if the linked PR doesn't work for you. (This and cryptic support in general is for block-style cryptics; bar-style would require some bigger layout changes to the player.)
